p8105\_hw2\_hx2263
================
Tiffany Xi
2018-09-27

Problem 1
---------

**Import and clean NYC transit csv files**

``` r
nyc_transit = 
  read_csv(file = "./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>% 
  janitor::clean_names() %>% 
  select(line, station_name, station_latitude, station_longitude, starts_with("route"), entry,          vending, entrance_type, ada) %>% 
  mutate(entry = recode(entry, "YES" = TRUE, "NO" = FALSE))
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_character(),
    ##   `Station Latitude` = col_double(),
    ##   `Station Longitude` = col_double(),
    ##   Route8 = col_integer(),
    ##   Route9 = col_integer(),
    ##   Route10 = col_integer(),
    ##   Route11 = col_integer(),
    ##   ADA = col_logical(),
    ##   `Free Crossover` = col_logical(),
    ##   `Entrance Latitude` = col_double(),
    ##   `Entrance Longitude` = col_double()
    ## )

    ## See spec(...) for full column specifications.

``` r
nyc_transit
```

    ## # A tibble: 1,868 x 19
    ##    line  station_name station_latitude station_longitu… route1 route2
    ##    <chr> <chr>                   <dbl>            <dbl> <chr>  <chr> 
    ##  1 4 Av… 25th St                  40.7            -74.0 R      <NA>  
    ##  2 4 Av… 25th St                  40.7            -74.0 R      <NA>  
    ##  3 4 Av… 36th St                  40.7            -74.0 N      R     
    ##  4 4 Av… 36th St                  40.7            -74.0 N      R     
    ##  5 4 Av… 36th St                  40.7            -74.0 N      R     
    ##  6 4 Av… 45th St                  40.6            -74.0 R      <NA>  
    ##  7 4 Av… 45th St                  40.6            -74.0 R      <NA>  
    ##  8 4 Av… 45th St                  40.6            -74.0 R      <NA>  
    ##  9 4 Av… 45th St                  40.6            -74.0 R      <NA>  
    ## 10 4 Av… 53rd St                  40.6            -74.0 R      <NA>  
    ## # ... with 1,858 more rows, and 13 more variables: route3 <chr>,
    ## #   route4 <chr>, route5 <chr>, route6 <chr>, route7 <chr>, route8 <int>,
    ## #   route9 <int>, route10 <int>, route11 <int>, entry <lgl>,
    ## #   vending <chr>, entrance_type <chr>, ada <lgl>

*Description:*

This nyc\_transit dataset contains variables named line, station\_name, station\_latitude, station\_longitude, route1, route2, route3, route4, route5, route6, route7, route8, route9, route10, route11, entry, vending, entrance\_type, ada.

My data cleaning steps are: first clean the column names into snake case with function janitor::clean\_names; then use 'select' function to select the variables I am interested in. Subsequently, use recode to convert the character variable 'YES' and 'NO' in 'entry' column into logical variable 'TRUE' and 'FALSE'.

The dimension of the resulting dataset is 1868\*19.

*Answers:*

1.There are 465 distinct stations.

**filter out the ADA complicant distinct stations**

``` r
ada_nyc_transit = 
  nyc_transit %>% 
  distinct(line, station_name, .keep_all = TRUE) %>% 
  filter(ada == "TRUE")
```

2.The number of stations which are ADA compliant is 84.

``` r
vend_nyc_transit =
  nyc_transit %>%
  filter(vending == 'NO')
nrow(vend_nyc_transit)/nrow(nyc_transit)
```

    ## [1] 0.09796574

Reformat the data

1.route number and route name are distinct variables

``` r
nyc_transit_tidy = 
  nyc_transit%>% 
  gather(key = "route_number", value = "route_name", route1:route11)
```

2.find out the distinct stations serve the A train

``` r
nyc_transit_tidy_a = 
  nyc_transit_tidy %>% 
  distinct(line, station_name, .keep_all = TRUE) %>% 
  filter(route_name == "A")
```

60 distinct stations serve the A train.

``` r
nyc_transit_tidy_a_ada = 
  nyc_transit_tidy_a %>% 
  filter(ada == "TRUE")
```

Of the stations that serve the A train, 17 of them are ADA compliant.

Problem 2
---------

1.Read and clean the Mr. Trash Wheel sheet.

``` r
trash_wheel = 
  readxl::read_excel(path = "./data/HealthyHarborWaterWheelTotals2017-9-26.xlsx", 
                     sheet = "Mr. Trash Wheel", 
                     range = "A2:N258") %>%
  janitor::clean_names() %>% 
  filter(!is.na(dumpster)) %>% 
  mutate(sports_balls = round(sports_balls, digits = 0)) %>% 
  mutate(sports_balls = as.integer(sports_balls))
trash_wheel
```

    ## # A tibble: 215 x 14
    ##    dumpster month  year date                weight_tons volume_cubic_ya…
    ##       <dbl> <chr> <dbl> <dttm>                    <dbl>            <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31               18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74               13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45               15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06               18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71               13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52               14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76               18
    ## # ... with 205 more rows, and 8 more variables: plastic_bottles <dbl>,
    ## #   polystyrene <dbl>, cigarette_butts <dbl>, glass_bottles <dbl>,
    ## #   grocery_bags <dbl>, chip_bags <dbl>, sports_balls <int>,
    ## #   homes_powered <dbl>

2.Read and clean precipitation data for 2016 and 2017

``` r
prcp_2016 = 
  readxl::read_excel(path = "./data/HealthyHarborWaterWheelTotals2017-9-26.xlsx",
                     sheet = "2016 Precipitation", 
                     range = "A2:B15") %>% 
  janitor::clean_names() %>% 
  filter(!is.na(month)) %>% 
  filter(!is.na(total)) %>% 
  mutate(year = 2016) 

prcp_2016
```

    ## # A tibble: 12 x 3
    ##    month total  year
    ##    <dbl> <dbl> <dbl>
    ##  1     1  3.23  2016
    ##  2     2  5.32  2016
    ##  3     3  2.24  2016
    ##  4     4  1.78  2016
    ##  5     5  5.19  2016
    ##  6     6  3.2   2016
    ##  7     7  6.09  2016
    ##  8     8  3.96  2016
    ##  9     9  4.53  2016
    ## 10    10  0.62  2016
    ## 11    11  1.47  2016
    ## 12    12  2.32  2016

``` r
prcp_2017 = 
  readxl::read_excel(path = "./data/HealthyHarborWaterWheelTotals2017-9-26.xlsx",
                     sheet = "2017 Precipitation", 
                     range = "A2:B15") %>% 
  janitor::clean_names() %>% 
  filter(!is.na(month)) %>% 
  filter(!is.na(total)) %>% 
  mutate(year = 2017) 

prcp_2017
```

    ## # A tibble: 8 x 3
    ##   month total  year
    ##   <dbl> <dbl> <dbl>
    ## 1     1  2.34  2017
    ## 2     2  1.46  2017
    ## 3     3  3.57  2017
    ## 4     4  3.99  2017
    ## 5     5  5.64  2017
    ## 6     6  1.4   2017
    ## 7     7  7.09  2017
    ## 8     8  4.44  2017

3.Combine datasets and convert month to a character variable

``` r
prcp_2016 = mutate(prcp_2016, month = month.name)
prcp_2017 = mutate(prcp_2017, month = month.name[0:nrow(prcp_2017)])
combo_16_17 = full_join(prcp_2016, prcp_2017)
```

    ## Joining, by = c("month", "total", "year")

``` r
combo_16_17
```

    ## # A tibble: 20 x 3
    ##    month     total  year
    ##    <chr>     <dbl> <dbl>
    ##  1 January    3.23  2016
    ##  2 February   5.32  2016
    ##  3 March      2.24  2016
    ##  4 April      1.78  2016
    ##  5 May        5.19  2016
    ##  6 June       3.2   2016
    ##  7 July       6.09  2016
    ##  8 August     3.96  2016
    ##  9 September  4.53  2016
    ## 10 October    0.62  2016
    ## 11 November   1.47  2016
    ## 12 December   2.32  2016
    ## 13 January    2.34  2017
    ## 14 February   1.46  2017
    ## 15 March      3.57  2017
    ## 16 April      3.99  2017
    ## 17 May        5.64  2017
    ## 18 June       1.4   2017
    ## 19 July       7.09  2017
    ## 20 August     4.44  2017

``` r
combo_16_17_trash = full_join(combo_16_17, trash_wheel, by = c("month", "year"))
combo_16_17_trash
```

    ## # A tibble: 217 x 15
    ##    month total  year dumpster date                weight_tons
    ##    <chr> <dbl> <dbl>    <dbl> <dttm>                    <dbl>
    ##  1 Janu…  3.23  2016      116 2016-01-10 00:00:00        3.6 
    ##  2 Febr…  5.32  2016      117 2016-02-02 00:00:00        4.06
    ##  3 Febr…  5.32  2016      118 2016-02-03 00:00:00        2.11
    ##  4 Febr…  5.32  2016      119 2016-02-05 00:00:00        3.01
    ##  5 Febr…  5.32  2016      120 2016-02-17 00:00:00        3.41
    ##  6 Febr…  5.32  2016      121 2016-02-19 00:00:00        3.66
    ##  7 Febr…  5.32  2016      122 2016-02-25 00:00:00        4.51
    ##  8 March  2.24  2016      123 2016-03-01 00:00:00        2.89
    ##  9 March  2.24  2016      124 2016-03-11 00:00:00        2.89
    ## 10 March  2.24  2016      125 2016-03-12 00:00:00        2.51
    ## # ... with 207 more rows, and 9 more variables: volume_cubic_yards <dbl>,
    ## #   plastic_bottles <dbl>, polystyrene <dbl>, cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   sports_balls <int>, homes_powered <dbl>

the number of observations in both resulting datasets are 215 and 20, and give examples of key variables.

For available data, the total precipitation in 2017 was 29.93.

The median number of sports balls in a dumpster in 2016 was 141.
